name: Build Kivy APK with Buildozer

on: [push]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies and buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.34
          # [SỬA LỖI] Sửa "i3D" thành "i386"
          sudo dpkg --add-architecture i386
          sudo apt-get update
          # [SỬA LỖI] Sửa "libz1:i386" thành "zlib1g:i386" và đảm bảo không lặp lại zlib1g-dev
          sudo apt-get install -y libc6:i386 libncurses6:i386 libstdc++6:i386 zlib1g:i386 libssl-dev libjpeg-dev

      - name: Build with Buildozer
        run: |
          buildozer --log-level debug android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sok-wallet-apk
          path: bin/*.apk
