name: Build Kivy APK with Buildozer

on: [push]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # --- [SỬA LỖI TOÀN DIỆN] ---
      # Bước 1: Thiết lập môi trường Java (bắt buộc cho Android SDK)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Bước 2: Thiết lập môi trường Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Bước 3: Cài đặt các thư viện hệ thống
      - name: Install system dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y libc6:i386 libncurses6:i386 libstdc++6:i386 zlib1g:i386 libssl-dev libjpeg-dev

      # Bước 4: Cài đặt Buildozer và các thư viện Python
      - name: Install Buildozer and Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.34

      # Bước 5: Tải về các công cụ Android và chấp nhận giấy phép một cách tường minh
      - name: Download Android SDK and accept licenses
        run: |
          # ANDROID_HOME là biến môi trường chuẩn cho Android SDK
          export ANDROID_HOME=$HOME/android-sdk
          # Tạo thư mục cmdline-tools để chứa sdkmanager
          mkdir -p $ANDROID_HOME/cmdline-tools
          # Tải về bộ công cụ dòng lệnh
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          # Giải nén vào thư mục cmdline-tools và đổi tên thành 'latest'
          unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools/
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          # Thêm sdkmanager vào PATH để có thể gọi trực tiếp
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
          # Chạy sdkmanager để chấp nhận tất cả các giấy phép và cài đặt build-tools
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-31" "build-tools;34.0.0" "platform-tools"

      # Bước 6: Chạy Buildozer (giờ đây môi trường đã hoàn toàn sẵn sàng)
      - name: Build with Buildozer
        run: |
          buildozer android debug --log-level 2

      # Bước 7: Tải APK lên
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sok-wallet-apk
          path: bin/*.apk
