name: Build Kivy APK with Buildozer

on: [push]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies including build tools
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          # [SỬA LỖI QUAN TRỌNG] Thêm autoconf, automake, và libtool
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            build-essential \
            autoconf \
            automake \
            libtool \
            pkg-config \
            libc6:i386 \
            libncurses6:i386 \
            libstdc++6:i386 \
            zlib1g:i386 \
            libssl-dev \
            libjpeg-dev

      - name: Install Buildozer and Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.34

      # Các bước Download Android SDK và Buildozer giữ nguyên từ phiên bản trước

      - name: Download Android SDK, accept licenses, and create compatibility symlinks
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          mkdir -p $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools/
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
          yes | sdkmanager --licenses
          sdkmanager --sdk_root=${ANDROID_HOME} "platforms;android-31" "build-tools;34.0.0" "platform-tools"
          
          mkdir -p $ANDROID_HOME/tools/bin
          ln -s $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager $ANDROID_HOME/tools/bin/sdkmanager
          ln -s $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager $ANDROID_HOME/tools/bin/avdmanager

      - name: Build with Buildozer
        run: |
          buildozer android debug --log-level 2

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sok-wallet-apk
          path: bin/*.apk
