name: Build Kivy APK with Buildozer

on: [push]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies and buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.34
          sudo dpkg --add-architecture i386
          sudo apt-get update
          # [SỬA LỖI] Cài đặt các thư viện hệ thống cần thiết cho cryptography và pillow
          sudo apt-get install -y libc6:i386 libncurses5:i386 libstdc++6:i386 libz1:i386 libssl-dev libjpeg-dev zlib1g-dev

      - name: Build with Buildozer
        run: |
          # Thêm cờ --log-level 2 để có log chi tiết hơn khi cần
          buildozer --log-level 2 -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sok-wallet-apk
          path: bin/*.apk
