name: Build Kivy APK with Buildozer

on: [push]

jobs:
  build-android:
    # Sử dụng Ubuntu 22.04 ổn định
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip build-essential autoconf libtool pkg-config \
            libc6:i386 libncurses6:i386 libstdc++6:i386 zlib1g:i386

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.34

      # [GIẢI PHÁP CUỐI CÙNG] Chuẩn bị sẵn môi trường SDK cho Buildozer
      - name: Prepare Buildozer SDK environment
        run: |
          # Đây là thư mục SDK mà Buildozer sẽ tự động tạo ra và kiểm tra
          export BUILDOZER_SDK_PATH="/home/runner/.buildozer/android/platform/android-sdk"
          
          # Tải về command line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          
          # Tạo thư mục và giải nén vào đúng cấu trúc mà sdkmanager yêu cầu
          mkdir -p $BUILDOZER_SDK_PATH/cmdline-tools
          unzip cmdline-tools.zip -d $BUILDOZER_SDK_PATH/cmdline-tools
          mv $BUILDOZER_SDK_PATH/cmdline-tools/cmdline-tools $BUILDOZER_SDK_PATH/cmdline-tools/latest
          
          # Chạy sdkmanager để chấp nhận giấy phép và cài đặt build-tools VÀO ĐÚNG THƯ MỤC CỦA BUILDOZER
          echo "y" | $BUILDOZER_SDK_PATH/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null
          $BUILDOZER_SDK_PATH/cmdline-tools/latest/bin/sdkmanager --sdk_root=${BUILDOZER_SDK_PATH} "platforms;android-31" "build-tools;34.0.0" "platform-tools"

      - name: Build with Buildozer
        run: |
          buildozer android debug --log-level 2

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sok-wallet-apk
          path: bin/*.apk
