name: Build Kivy APK with Buildozer

on: [push]

jobs:
  build-android:
    # [SỬA LỖI QUAN TRỌNG NHẤT] Sử dụng một phiên bản Ubuntu ổn định và đã được kiểm chứng
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            build-essential \
            autoconf \
            libtool \
            pkg-config \
            libc6:i386 \
            libncurses6:i386 \
            libstdc++6:i386 \
            zlib1g:i386

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.34

      - name: Build with Buildozer
        run: |
          buildozer android debug --log-level 2

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sok-wallet-apk
          path: bin/*.apk
