name: Build Kivy APK with Buildozer

on: [push]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y libc6:i386 libncurses6:i386 libstdc++6:i386 zlib1g:i386 libssl-dev libjpeg-dev

      - name: Install Buildozer and Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.34

      - name: Download Android SDK, accept licenses, and create compatibility symlinks
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          mkdir -p $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools/
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
          yes | sdkmanager --licenses
          sdkmanager --sdk_root=${ANDROID_HOME} "platforms;android-31" "build-tools;34.0.0" "platform-tools"

          # [SỬA LỖI QUAN TRỌNG] TẠO CẤU TRÚC THƯ MỤC CŨ ĐỂ "ĐÁNH LỪA" BUILDOZER
          # Tạo thư mục tools/bin mà Buildozer đang tìm kiếm
          mkdir -p $ANDROID_HOME/tools/bin
          # Tạo một liên kết tượng trưng (symlink) từ sdkmanager thật đến vị trí ảo
          ln -s $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager $ANDROID_HOME/tools/bin/sdkmanager
          # Làm tương tự cho avdmanager để tránh lỗi tiềm ẩn
          ln -s $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager $ANDROID_HOME/tools/bin/avdmanager

      - name: Build with Buildozer
        run: |
          buildozer android debug --log-level 2

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sok-wallet-apk
          path: bin/*.apk
